# Puerto INTERNO en el que correrá la aplicación dentro del contenedor
server:
  port: 8080

spring:
  application:
    name: ecommerce
  datasource:
    # URL de conexión a MySQL. 
    # 'mysql-ecommerce-prod' DEBE ser el nombre del servicio de MySQL en tu docker-compose.yml
    url: jdbc:mysql://mysql-ecommerce-prod:3306/ecommerce_db?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    # Usuario y contraseña que deben coincidir con las variables de entorno en tu docker-compose.yml
    username: root
    password: admin123 # Asegúrate que esta es la contraseña correcta (en el compose era 'admin')
  jpa:
    hibernate:
      # 'update' permite a Hibernate crear/modificar tablas basado en tus entidades Java
      ddl-auto: update
    # Muestra el SQL en la consola, muy útil para depurar
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

# Configuración del Actuator para el health check
management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    org.hibernate.sql: debug
    org.springframework.web: INFO
