server:
  port: 8080

spring:
  application:
    name: ecommerce
  datasource:
    url: jdbc:mysql://db:3306/ecommerce_lp2_prod?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health