version: '3.8'

services:
  # Servicio de la Base de Datos
  db:
    image: mysql:8.0
    container_name: mysql-ecommerce-prod
    restart: always
    environment:
      MYSQL_DATABASE: 'ecommerce_lp2_prod'
      MYSQL_ROOT_PASSWORD: 'admin123'
    volumes:
      - mysql_data:/var/lib/mysql
      - ../sql:/docker-entrypoint-initdb.d/
    # --- AÑADE ESTAS DOS LÍNEAS ---
    ports:
      - "3306:3306"
    # -----------------------------
    networks:
      - backend

  # Servicio de la Aplicación
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: product_app
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8084:8080"
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
    name: ecommerce_net