# docker-compose by aaronchelo18

version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql-ecommerce-prod
    restart: always
    environment:
      MYSQL_DATABASE: 'ecommerce_lp2_prod'
      MYSQL_ROOT_PASSWORD: 'admin123'
    volumes:
      - mysql_data:/var/lib/mysql
      - ../sql:/docker-entrypoint-initdb.d/
    ports:
      - "3310:3306"
    networks:
      - backend
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: product_app
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8085:8080"
    networks:
      - backend
volumes:
  mysql_data:
networks:
  backend:
    name: ecommerce_net