version: '3.8'

services:
  # Servicio de la Base de Datos
  db:
    image: mysql:8.0
    container_name: mysql-ecommerce-prod
    restart: always
    environment:
      MYSQL_DATABASE: 'ecommerce_lp2_prod'
      MYSQL_ROOT_PASSWORD: 'admin123'
    volumes:
      - mysql_data:/var/lib/mysql
      - ../sql:/docker-entrypoint-initdb.d/
    networks:
      - backend

  # Servicio de la Aplicación
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: product_app
    restart: on-failure
    depends_on:
      - db
    ports:
      # Mapea el puerto 8084 del HOST al puerto 8080 del CONTENEDOR
      - "8084:8080"
    # No necesitamos variables de entorno aquí, ya que todo está en application.yml
    # Esto evita conflictos y mantiene la configuración en un solo lugar.
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
    name: ecommerce_net